{
	names=[
	{"name":"Bondith","province":"PhnomPenh"},
	{"name":"Vira","province":"PhnomPenh"},
	{"name":"Ponler","province":"Kompot"},
	{"name":"Vanna","province":"BatDomBong"},
	{"name":"Vichea","province":"BonteayMeanChey"}
	]
}
